[tool.poetry]
name = "tutle-langchain"
version = "0.1.0"
description = ""
authors = ["Elisar Chodorov <elisarchod@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
langgraph = "^0.2.53"
langchain = "^0.3.7"
langsmith = "^0.1.143"
langchain-pinecone = "^0.2.0"
langchain-openai = "^0.2.11"
python-dotenv = "^1.0.1"
langchain-anthropic = "^0.3.0"
langchain-community = "^0.3.10"
bs4 = "^0.0.2"
fastapi = "^0.115.6"
langgraph-cli = {extras = ["inmem"], version = "^0.1.65"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
