[tool.poetry]
name = "llm-langchain"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langgraph = "^0.2.53"
langchain = "^0.3.7"
langsmith = "^0.1.143"
langchain-pinecone = "^0.2.0"
langchain-openai = "^0.2.11"
python-dotenv = "^1.0.1"
langchain-anthropic = "^0.3.0"
langchain-community = "^0.3.10"
bs4 = "^0.0.2"
fastapi = "^0.115.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
