name: Build and Push Docker Image

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  pull_request:
    branches: [main] # Trigger on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Important: Grants write permission to GHCR
    steps:
      - uses: actions/checkout@v3

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: . # Current directory as build context
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }} # Tag with commit SHA
          cache-from: type=gha
          cache-to: type=gha,mode=max
